background_opacity 0.87
# ======================
# FONT
# ======================
font_family      JetBrainsMono Nerd Font
font_size        12.5

# ======================
# WINDOW / DECORATIONS
# ======================
hide_window_decorations yes

# ======================
# SCROLLBAR
# ======================
# scrollbar_width 4

# ======================
# COLORS
# ======================

# Background (do seu foot: #131313)
background #131313

# Foreground (comentado no foot = padrão do tema)
# foreground #ffffff

# --- Cores regulares ---
# color0  #000000   # black       (comentado)
# color1  #ff5555   # red         (comentado)
# color2  #50fa7b   # green       (comentado)
# color3  #f1fa8c   # yellow      (comentado)
# color4  #bd93f9   # blue        (comentado)
color5  #c796c0    # magenta     (comentado)
color6  #00ced1     # cyan        (ATIVO)
# color7  #bfbfbf   # white       (comentado)

# --- Cores brilhantes ---
# color8  #4d4d4d   # bright black  (comentado)
# color9  #ff6e67   # bright red    (comentado)
# color10 #5af78e   # bright green  (comentado)
# color11 #f4f99d   # bright yellow (comentado)
# color12 #caa9fa   # bright blue   (comentado)
# color13 #ff92d0   # bright magenta(comentado)
# color14 #9aedfe   # bright cyan   (comentado)
# color15 #e6e6e6   # bright white  (comentado)
