[main]
font=JetBrainsMono Nerd Font:size=13.5
prompt="> "
# Ajuste a largura (em caracteres) conforme necessário
width=30 

[colors]
# Fundo escuro solido (#1e1e1e)
background=1e1e1eff
# Texto padrão (#cccccc)
text=ccccccff
# Cor do texto ao digitar (#f8f8f2)
match=f8f8f2ff
# Fundo do item selecionado (#3e3e3e)
selection=3e3e3eff
# Texto do item selecionado (#ffffff)
selection-text=ffffffff
selection-match=ffffffff
# Borda sutil (#333333)
border=333333ff

[border]
# O fuzzel separa a espessura e o raio do border em uma sessão própria
width=1
radius=8
