[[language]]
name = "c"
auto-format = false
language-servers = ["clangd"]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "cpp"
auto-format = false
language-servers = ["clangd"]
indent = { tab-width = 4, unit = "    " }
